# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Mary Gentile
email: "black.roses9995@gmail.com"
description: >
  College student looking to showcase her knowledge and abilities in order to obtain a co-op/internship in a HCC related field.
about_me: >
  I'm a Human Centered Computing student at Rochester Institute of Technology looking to put my design and technical skills, along with my understanding of the human cognitive processes, to use creating fluid and aesthetically pleasing designs. I have a passion for reading, video games, UX/UI design, and archery.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blackroses9995.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
linked_in_link: "https://www.linkedin.com/in/mgentile1999"
github_link: "https://www.github.com/blackroses9995"
twitter_username: "black_roses9995"
google_analytics_id: 'UA-117297510-1'
select_options: clear-filters HTML5 CSS3 SCSS javaScript jQuery materialize charts.js React jekyll Ruby-on-Rails Sinatra front-end back-end finished current
sass:
  sass_dir: assets/css/main.css
  style: :nested

gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
